### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by simonitfi** [olliglorioso/linear-regression-ts#6]
Hello getting following error:

TypeError
Cannot read properties of undefined (reading 'length')
shuffleList
https://xe8zh1.csb.app/node_modules/linear-regression-ts/dist/utils.js:6:31
trainAndTestSets
https://xe8zh1.csb.app/node_modules/linear-regression-ts/dist/index.js:19:72
App
/src/App.js:94:78
```
  91 | // Create train and test sets. One column for one feature.
  92 | const x = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [9, 10], [10, 11]]
  93 | const y = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> 94 | const { trainValues, testValues, trainLabels, testLabels } = trainAndTestSets({ x, y, ratio: 0.7 })  
```

**Comment by olliglorioso** [comment]
Hi @simonitfi

Thank you for reporting. My apologies, the README was outdated and the parameter names didn't match the current code.  Note that also some other changes were made to the README. Now published a new version to npm.

**Comment by simonitfi** [comment]
Hello,

Thank you for quick reply. I’m new on these functions, and I’m trying to predict time when temperature will reach the target (for example 30.0) with data where is current temperature increments with timestamp and  temperature. Like this:

const data = [
  [1665832383,23.1],
  [1665832391,23.2],
  [1665832424,23.3],
  [1665832688,23.4],
  [1665832689,23.5],
  [1665832692,23.5],
  [1665832697,23.6],
  [1665832711,23.7],
  [1665832722,23.8],
  [1665832727,23.7],
  ];

Could you point me out, how should I put the  values to this concept:

const x = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [9, 10], [10, 11]]
const y = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


I tried some variation without any luck.

**Comment by olliglorioso** [comment]
Hi @simonitfi ,
I got some results with the following parameters with your data:
````typescript
const x = [
    [1665832383],
    [1665832391],
    [1665832424],
    [1665832688],
    [1665832689],
    [1665832692],
    [1665832697],
    [1665832711],
    [1665832722],
    [1665832727],
];
const y = [
    23.1,
    23.2,
    23.3,
    23.4,
    23.5,
    23.5,
    23.6,
    23.7,
    23.8,
    23.7,
];

const iterations = 50000000
const learningRate1 = 0.0000000000000000000000001

````

Inputs are in the format [[feature1, feature2, ...], [feature1, feature2, ...], ...] where one row is one measurement. In your case, you have only one feature, which is the temperature. The labels are in the format [label1, label2, ...] where one row (also one element in the list) is the label for corresponding measurement. 

As your dataset is very small and for every little change in the timestamp there is huge leap in the temperatures, the results are pretty bad. 

Console output is the following:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/84347872/196639404-7ec8cd17-4a08-4b35-a8fb-cf2b21d5d187.png">

Overrall, I think your dataset would be more realistic, if the measurements were for example 10 minutes per temperature, since I the temperature doesn't really change in the matter of milliseconds like in your dataset. I tried to use these values: 
````typescript
const x = [
    [10],
    [20],
    [30],
    [40],
    [50],
    [60],
    [70],
    [80],
    [90],
    [100],
];
const y = [
    23.1,
    23.2,
    23.3,
    23.4,
    23.5,
    23.5,
    23.6,
    23.7,
    23.8,
    23.7,
];
//stuff here
const iterations = 500000
const learningRate1 = 0.0001
````
With the following console output: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/84347872/196641816-57c7cc19-49e7-402f-9ade-39d3bf8cb708.png">
This seems to work a lot better. For better results use bigger iteration amount and maybe a bit smaller learningRate1.

**Comment by olliglorioso** [comment]
I close this issue but you can still ask for help in this ticket.

**Comment by simonitfi** [comment]
Hello, 

yes, thank you, you are right, I could use seconds after initial value, so then the timestamp is much smaller value. Anyway, now I'm looking how to predict the time for the temperature reach for example 60 degrees. 


```
// Create train and test sets. One column for one feature.
  const {
    trainValues,
    testValues,
    trainLabels,
    testLabels
  } = trainAndTestSets({ inputs: timeA, labels: data, ratio: 50 });

  // Initialize the untrain
  const lr2 = new LinearRegression({
    inputs: trainValues,
    labels: trainLabels
  });

  // Train the model.
  const iterations = 500000;
  const learningRate1 = 0.0001;

  const logging = true;
  const optimizeStartingWeights = true;
  const { intercept, slopes, error } = lr2.fit({
    iterations,
    learningRate: learningRate1,
    logging,
    optimizeStartingWeights
  });

  // Set custom intercept and slope. Let's set the ones we got previously.
  lr2.setModel({ slopes, intercept });

  // Test the model, and get the evaluation of its performance.
  const { mse, mae } = lr2.scores({ testValues, testLabels });
  console.log("MSE", mse, "MAE " + mae);

  // Predict unknown values.
  const predictions = lr2.predict({ inputs: testValues });
  let a = 0;
  for (const i of predictions) {
    console.log("Prediction:", i, "Real value:", testLabels[a]);
    a++;
  }
  let arr = [];
  arr.push([60]);

  const pre = lr2.predict({ inputs: arr });
  console.log("predict", pre);

```

Getting output:
MSE 0.00844291362767976 MAE 0.07464651829474889 
Prediction: 23.831565743949085 Real value: 23.7
Prediction: 23.295201910285815 Real value: 23.3
Prediction: 23.02701999345418 Real value: 23.2
Prediction: 23.56338382711745 Real value: 23.5
Prediction: 23.42929286870163 Real value: 23.4
Prediction: 23.65277779939466 Real value: 23.6
Prediction: 23.161110951869997 Real value: 23.2
Prediction: 23.071716979592786 Real value: 23.2
Prediction: 23.518686840978845 Real value: 23.5
Prediction: 23.2058079380086 Real value: 23.1
predict {}

the  lr2.predict({ inputs: arr }) does not return anything? Please any ideas?

**Comment by olliglorioso** [comment]
Hi @simonitfi 

The _predict_-function returns a **generator** as the types suggest: 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/84347872/197333637-5bc96518-f5ea-4941-91cb-4d41c59a2148.png">
so you have to loop through it with code such as 
```typescript
for (const a of pre) console.log(a)
```
Maybe I should add an option to choose whether the user wants to get the values as a generator or list.

In addition, to get the time when your predictions reach 60 degrees, you have to give the times as a label, and then search for the prediction of 60 degrees. So like the other way around, you tried to give the temperature as a input and get the time. So something like this in the end of your code:
```typescript
let arr = [];
for (const i of [...Array(1000).keys()]) {
  arr.push([i])
}

let b = 0
const pre = lr2.predict({ inputs: arr });
for (const i of pre) {
  console.log(i, "seconds is", b)
  b++
}
console.log("predict", pre);
```
I could also implement this kind of feature to this module.

**Comment by simonitfi** [comment]
Hi,

this would be nice if you add that, so no need to try to find close value.

Anyway, tried your suggestion for predicting multiple values, anyway result is strange with following training data.

  ```
const train = [
    [0, 23.2],
    [30, 23.2],
    [50, 23.1],
    [70, 23.2],
    [80, 23.1],
    [90, 23.2],
    [100, 23.3],
    [120, 23.4],
    [130, 23.4],
    [150, 23.4],
    [160, 23.5],
    [180, 23.5],
    [190, 23.5],
    [220, 23.6],
    [230, 23.6],
    [240, 23.7],
    [260, 23.7],
    [290, 23.8],
    [300, 23.7]
  ];

  const time = train.map((d) => d[0]);
  const data = train.map((d) => d[1]);
  let timeA = [];

  for (const item in time) {
    timeA.push([item]);
  }
  const {
    trainValues,
    testValues,
    trainLabels,
    testLabels
  } = trainAndTestSets({ inputs: timeA, labels: data, ratio: 50 });
```

for example:
44.474008209040164 "seconds is" 599

so doubling the time will result from 23.7 -> 44.4 in same time when training data goes below one degree?

**Comment by olliglorioso** [comment]
I'm quite buzy days today and tomorrow, so I'll respond you on Tuesday probably.

**Comment by simonitfi** [comment]
> I'm quite buzy days today and tomorrow, so I'll respond you on Tuesday probably.

Okay, no worries :)
